[project]
site_name = "testdesiderata"
site_url = "https://benomahony.github.io/testdesiderata"
site_description = "Add your description here"
site_author = "benomahony"
copyright = "&copy; 2026 benomahony"
docs_dir = "docs"
site_dir = "site"
use_directory_urls = true

[project.theme]
variant = "modern"
